version: '3.7'
services:
  weaviate:
    image: semitechnologies/weaviate:1.25.6
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  worker:
    build: ..
    command: sh -c "cd Agent && celery -A celery_app.celery_app worker -l info"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - WEAVIATE_HOST=http://weaviate:8080
    depends_on:
      - redis
      - weaviate
volumes:
  weaviate_data: